import localFont from "next/font/local";
import "./globals.css";
import BootComponent from "./components/BootComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "A1Trading",
  description: "Generated by Devkumar Parekh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootComponent>{children}</BootComponent>
      </body>
    </html>
  );
}
